from .cnae import AkiCnaeReader
from .company import AkiCompanyReader
from .natureza_juridica import AkiNaturezaJuridicaReader
from .municipio import AkiMunicipioReader
from .pais import AkiPaisReader
from .simples import AkiSimplesReader
from .situacao_cadastral import AkiSituacaoCadastralReader
from .estabelecimento import AkiEstabelecimentoReader
from .socios import AkiSociosReader
